# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/bionic64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  #config.vm.synced_folder "../data", "/vagrant_data"
  
  # X forwarding
  config.ssh.forward_x11 = true

  # Agent forwarding
  config.ssh.forward_agent = true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
  # Display the VirtualBox GUI when booting the machine
  #vb.gui = true
  
  # Customize the amount of memory on the VM:
  vb.memory = "2048"

  # Disk size, requires:
  # vagrant plugin install vagrant-disksize
  config.disksize.size = '20GB'

  # Audio (Linux)
  vb.customize ["modifyvm", :id, "--ioapic", "on", '--audio', 'pulse', '--audiocontroller', 'ac97'] 
  #vb.customize ["modifyvm", :id, "--ioapic", "on", '--audio', 'alsa', '--audiocontroller', 'hda'] 
  # Audio (Windows) # Not tested
  #vb.customize ["modifyvm", :id, "--ioapic", "on", '--audio', 'dsound', '--audiocontroller', 'hda'] 
  # Audio (MAC) # Not tested
  #vb.customize ["modifyvm", :id, "--ioapic", "on", '--audio', 'coreaudio', '--audiocontroller', 'hda'] 
  vb.customize ["modifyvm", :id, "--audioin", "off"]
  vb.customize ["modifyvm", :id, "--audioout", "on"]

  # USB 3.0
  vb.customize ["modifyvm", :id, "--usb", "on"]
  vb.customize ["modifyvm", :id, "--usbxhci", "on"]

  # Note
  # Add the devices you want here. Run lsusb to get the vendor/product ids.
  # You can also run virtualbox, click "show" on this vagrant machine, and then
  # use the GUI to add/remove USB devices (valid in general for any setting).  

  # SDRs
  vb.customize ['usbfilter', 'add', '0', '--target', :id, '--name', 'RTL2838 DVB-T', '--vendorid', '0x0bda', '--productid', '0x2838']
  vb.customize ['usbfilter', 'add', '0', '--target', :id, '--name', 'USPR B210', '--vendorid', '0x2500', '--productid', '0x0020']
  vb.customize ['usbfilter', 'add', '0', '--target', :id, '--name', 'HackRF', '--vendorid', '0x1d50', '--productid', '0x6089']
  
  # Phones
  #vb.customize ['usbfilter', 'add', '0', '--target', :id, '--name', 'Samsung Galaxy Mini S5', '--vendorid', '0x04e8', '--productid', '0x6860']
  end
    
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
  config.vm.provision :shell, path: "./bootstrap.sh", privileged: false
end
